@startuml
note "bleu: pas à changer, déjà existant\nvert: pas pour tout de suie" as N1

class MesaGraphics
MesaGraphics : start_loop()

class View
View : pygame_stuff
View : draw()
View : _draw_ui_element(UIElement)
View : _draw_button(Button)
View : _draw_slider(Slider)
View : _draw_component(Component)

class Controller
Controller : update()
Controller : update_ui_element(UIElement)
Controller : <color:green>update_component(Component)
Controller : _update_button(Button)
Controller : _update_slider(Slider)


class Model

MesaGraphics --> View
MesaGraphics --> Controller
MesaGraphics --> Model

/' ########## Controller part ########## '/

class InputHandler
InputHandler : update()
InputHandler : get_pressed(key)
InputHandler : get_holding(key)
InputHandler : get_released(key)

Controller --> InputHandler

/' ########## Model part ########## '/

class MesaModel
MesaModel : <color:blue> Model de mesa

Model --|> MesaModel

/' ##########  View part ########## '/

class Card
Card : position
Card : size
Card : scroll_position
View --> Card

class Component
Component : <color:green>is_image_updated
Component : page
Component : image
Component : update_image()
Card --> Component

class UIElement
UIElement : position
UIElement : size
Card --> UIElement

class UIButton
UIButton : text
UIButton : hover
UIElement --|> UIButton

class Slider
UIElement --|> Slider

class MesaSlider
MesaSlider : <color:blue>Slider de mesa
MesaSlider : <color:blue>min_value
MesaSlider : <color:blue>max_value
MesaSlider : <color:blue>step
MesaSlider : <color:blue>...
Slider --|> MesaSlider


@enduml