@startuml
note "bleu: pas à changer, déjà existant\nvert: pas pour tout de suie" as N1

class MesaGraphics
MesaGraphics : start_loop()

class View
View : pygame_stuff
View : draw()

class Controller
Controller : update()
Controller : <color:green>boutons/sliders

Controller -> View
Controller -> Model
View --> Model

MesaGraphics --> View
MesaGraphics --> Controller
MesaGraphics --> Model

/' ########## Controller part ########## '/

class InputHandler
InputHandler : update()
InputHandler : get_pressed(key)
InputHandler : get_holding(key)
InputHandler : get_released(key)

Controller --> InputHandler

/' ########## Model part ########## '/

class Model
Model : <color:blue> Model de mesa

/' ##########  View part ########## '/

class Component
Component : page
Component : image
Component : update_image()
Component : draw()
View --> Component

class UIElement
UIElement : position
UIElement : size
View --> UIElement

class UIButton
UIButton : <color:green>On verra pour l'action
UIElement <|-- UIButton

class Text
Text : text
UIButton --> Text
UIElement <|-- Text

class Slider
Slider : <color:green>On verra pour l'action
UIElement --|> Slider

class MesaSlider
MesaSlider : <color:blue>Slider de mesa
MesaSlider : <color:blue>min_value
MesaSlider : <color:blue>max_value
MesaSlider : <color:blue>step
MesaSlider : <color:blue>...
Slider --|> MesaSlider


@enduml