@startuml

abstract class AbstractRenderer
AbstractRenderer : initialize_canvas()
AbstractRenderer : draw_structure()
AbstractRenderer : collect_agent_data(space, agent_portrayal, default_size)
AbstractRenderer : draw_agents()
AbstractRenderer : draw_propertylayer(space, property_layers, propertylayer_portrayal)


class AltairBackend

class MatplotlibBackend

AltairBackend --|> AbstractRenderer
MatplotlibBackend --|> AbstractRenderer

class AgentPortrayalStyle
AgentPortrayalStyle : x
AgentPortrayalStyle : y
AgentPortrayalStyle : color
AgentPortrayalStyle : marker
AgentPortrayalStyle : size
AgentPortrayalStyle : zorder
AgentPortrayalStyle : AgentPortrayalStyle
AgentPortrayalStyle : edgecolors
AgentPortrayalStyle : linewidths
AgentPortrayalStyle : tooltip
AgentPortrayalStyle : update(updates_fields)

class PropertyLayerStyle
PropertyLayerStyle : colormap
PropertyLayerStyle : color
PropertyLayerStyle : alpha
PropertyLayerStyle : colorbar
PropertyLayerStyle : vmin
PropertyLayerStyle : vmax

AgentPortrayalStyle <-- SpaceRenderer
PropertyLayerStyle <-- SpaceRenderer

abstract class BaseSpaceDrawer
BaseSpaceDrawer : get_viz_limits()

AbstractRenderer --> BaseSpaceDrawer

class HexSpaceDrawer
class OrthogonalSpaceDrawer
class NetworkSpaceDrawer
class ContinuousSpaceDrawer
class VoronoiSpaceDrawer

HexSpaceDrawer : draw_matplotlib()
HexSpaceDrawer : draw_altair()
OrthogonalSpaceDrawer : draw_matplotlib()
OrthogonalSpaceDrawer : draw_altair()
NetworkSpaceDrawer : draw_matplotlib()
NetworkSpaceDrawer : draw_altair()
ContinuousSpaceDrawer : draw_matplotlib()
ContinuousSpaceDrawer : draw_altair()
VoronoiSpaceDrawer : draw_matplotlib()
VoronoiSpaceDrawer : draw_altair()

BaseSpaceDrawer <|-- HexSpaceDrawer
BaseSpaceDrawer <|-- OrthogonalSpaceDrawer
BaseSpaceDrawer <|-- NetworkSpaceDrawer
BaseSpaceDrawer <|-- ContinuousSpaceDrawer
BaseSpaceDrawer <|-- VoronoiSpaceDrawer

class SpaceRenderer
SpaceRenderer : model
SpaceRenderer : backend
SpaceRenderer : setup_structure()
SpaceRenderer : setup_agents(agent_portrayal:Callable)
SpaceRenderer : setup_propertylayer(propertylayer_portrayal: Callable)
SpaceRenderer : draw_structure()
SpaceRenderer : draw_agents(agent_portrayal:Callable)
SpaceRenderer : draw_propertylayer(propertylayer_portrayal: Callable)
SpaceRenderer : render(agent_portrayal, propertylayer_portrayal)
SpaceRenderer : post_process

SpaceRenderer -> AbstractRenderer
BaseSpaceDrawer --> SpaceRenderer


class UserParam
UserParam : maybeRaiseError()

class Slider
Slider : label
Slider : value
Slider : min
Slider : max
Slider : step

Slider -|> UserParam


class ComponentCreation
ComponentCreation : create_space_component(SpaceRenderer)
ComponentCreation : make_space_component(agent_portrayal, propertylayer_portrayal, post_process, backend)
ComponentCreation : make_altair_space(agent_portrayal, propertylayer_portrayal, post_process)
ComponentCreation : make_mpl_space_component(agent_portrayal, propertylayer_portrayal, post_process)
ComponentCreation : make_plot_component(measure, post_process, backend, page)
ComponentCreation : make_mpl_plot_component(measure, post_process, page)

OrthogonalSpaceDrawer -[hidden]-> ComponentCreation
ComponentCreation -[hidden]-> SolaraViz

ComponentCreation .> SpaceRenderer

class SolaraViz
SolaraViz : SolaraViz(model, renderer, components, play_interval, render_interval, simulator, model_params, name, use_threads)

SolaraViz .> SpaceRenderer

@enduml